### ISSUE TITLE
Simplification should only add back edge variables

### ISSUE THREAD

**Issue by curtisbright** [BrianLi009/PhysicsCheck#1]
https://github.com/BrianLi009/private_ks/blob/c7c1e0abd5bc3211547e453f18d15ff485742335/simplification/simplify.sh#L59

Hi Brian, we discussed this issue previously -- the simplification script shouldn't add removed non-edge variables back into the instance.  This is incorporated into simplify-by-var-removal.sh but the simplify.sh script adds back all variables.

I expect updating this will make the simplification process a bit more effective and therefore it may be optimal to run the simplification for a bit longer.  Could you fix this and rerun the simplification timings?  Thanks.

**Comment by BrianLi009** [comment]
Hi Curtis. Thanks for the comment, this task was indeed missed. I have made changes to simplify.sh, so that non-edge vars will not be added back into the instance.

Will update our simplification excel sheet with this. Thanks again.

**Comment by BrianLi009** [comment]
simp job resubmitted :)
