### ISSUE TITLE
New errors in pipeline

### ISSUE THREAD

**Issue by curtisbright** [BrianLi009/PhysicsCheck#9]
When running ./main.sh 16 I see the following:

verifying KS candidates of order 16 in 16.exhaust...
checking solutions are unique up to isomorphism...
0 candidates do not satisfy some constraints
constraint verification complete
checking embeddability of KS candidates using Z3...
using precomputed minimum nonembedable subgraph
enabling using minimal nonembeddable subgraph
wc: 16.exhaust-nonembeddable.txt: No such file or directory
nonembeddable candidates
0 embeddable candidates
0 Kochen-Specker candidates were found.
0 Kochen-Specker solutions were found.
./summary.sh 16 c 100000 2 2 0
expecting log files in the main directory
 n    Solving   Simplifying   Cubing 
16       0.00 m       0.04 m       0.00 m
(standard_in) 1: syntax error
maximum solvetime for a cube:       0.00 m

**Comment by BrianLi009** [comment]
moving this to the forked repo since all other issues are opened there, will merge it back later
